//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarfetchDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureToggle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeatureToggle()
        {
            this.ServiceFeatureToggle = new HashSet<ServiceFeatureToggle>();
        }
    
        public string Name { get; set; }
        public bool Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceFeatureToggle> ServiceFeatureToggle { get; set; }
    }
}
