//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarfetchDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFeatureToggle
    {
        public int ServiceId { get; set; }
        public string FeatureToggleName { get; set; }
        public Nullable<bool> CustomValue { get; set; }
    
        public virtual FeatureToggle FeatureToggle { get; set; }
        public virtual Services Services { get; set; }
    }
}
